export const PATHS = {
  config: "./config.ini",
};

export const ROWS_PER_PAGE = 40;

export const REG_NAMES = {
  11: "ILE-DE-FRANCE",
  24: "CENTRE-VAL DE LOIRE",
  27: "BOURGOGNE-FRANCHE-COMTE",
  28: "NORMANDIE",
  32: "HAUTS-DE-FRANCE",
  44: "GRAND EST",
  52: "PAYS DE LA LOIRE",
  53: "BRETAGNE",
  75: "NOUVELLE-AQUITAINE",
  76: "OCCITANIE",
  84: "AUVERGNE-RHONE-ALPES",
  93: "PROVENCE-ALPES-COTE D'AZUR",
  94: "CORSE",
  "01": "GUADELOUPE",
  "02": "MARTINIQUE",
  "03": "GUYANE",
  "04": "LA REUNION",
  "05": "SAINT-PIERRE-ET-MIQUELON",
  "06": "MAYOTTE",
  "07": "SAINT-BARTHELEMY",
  "08": "SAINT-MARTIN",
  "09": "WALLIS-ET-FUTUNA",
  "10": "POLYNESIE FRANCAISE",
  "12": "NOUVELLE-CALEDONIE" // (Le 11 est déjà pris par l'Île-de-France)
};

export const DEP_NAMES = {
  "01": "AIN",
  "02": "AISNE",
  "03": "ALLIER",
  "04": "ALPES-DE-HAUTE-PROVENCE",
  "05": "HAUTES-ALPES",
  "06": "ALPES-MARITIMES",
  "07": "ARDECHE",
  "08": "ARDENNES",
  "09": "ARIEGE",
  10: "AUBE",
  11: "AUDE",
  12: "AVEYRON",
  13: "BOUCHES-DU-RHONE",
  14: "CALVADOS",
  15: "CANTAL",
  16: "CHARENTE",
  17: "CHARENTE-MARITIME",
  18: "CHER",
  19: "CORREZE",
  "2A": "CORSE-DU-SUD",
  "2B": "HAUTE-CORSE",
  21: "COTE-D'OR",
  22: "COTES-D'ARMOR",
  23: "CREUSE",
  24: "DORDOGNE",
  25: "DOUBS",
  26: "DROME",
  27: "EURE",
  28: "EURE-ET-LOIR",
  29: "FINISTERE",
  30: "GARD",
  31: "HAUTE-GARONNE",
  32: "GERS",
  33: "GIRONDE",
  34: "HERAULT",
  35: "ILLE-ET-VILAINE",
  36: "INDRE",
  37: "INDRE-ET-LOIRE",
  38: "ISERE",
  39: "JURA",
  40: "LANDES",
  41: "LOIR-ET-CHER",
  42: "LOIRE",
  43: "HAUTE-LOIRE",
  44: "LOIRE-ATLANTIQUE",
  45: "LOIRET",
  46: "LOT",
  47: "LOT-ET-GARONNE",
  48: "LOZERE",
  49: "MAINE-ET-LOIRE",
  50: "MANCHE",
  51: "MARNE",
  52: "HAUTE-MARNE",
  53: "MAYENNE",
  54: "MEURTHE-ET-MOSELLE",
  55: "MEUSE",
  56: "MORBIHAN",
  57: "MOSELLE",
  58: "NIEVRE",
  59: "NORD",
  60: "OISE",
  61: "ORNE",
  62: "PAS-DE-CALAIS",
  63: "PUY-DE-DOME",
  64: "PYRENEES-ATLANTIQUES",
  65: "HAUTES-PYRENEES",
  66: "PYRENEES-ORIENTALES",
  67: "BAS-RHIN",
  68: "HAUT-RHIN",
  69: "RHONE",
  70: "HAUTE-SAONE",
  71: "SAONE-ET-LOIRE",
  72: "SARTHE",
  73: "SAVOIE",
  74: "HAUTE-SAVOIE",
  75: "PARIS",
  76: "SEINE-MARITIME",
  77: "SEINE-ET-MARNE",
  78: "YVELINES",
  79: "DEUX-SEVRES",
  80: "SOMME",
  81: "TARN",
  82: "TARN-ET-GARONNE",
  83: "VAR",
  84: "VAUCLUSE",
  85: "VENDEE",
  86: "VIENNE",
  87: "HAUTE-VIENNE",
  88: "VOSGES",
  89: "YONNE",
  90: "TERRITOIRE DE BELFORT",
  91: "ESSONNE",
  92: "HAUTS-DE-SEINE",
  93: "SEINE-SAINT-DENIS",
  94: "VAL-DE-MARNE",
  95: "VAL-D'OISE",
  971: "GUADELOUPE",
  972: "MARTINIQUE",
  973: "GUYANE",
  974: "LA REUNION",
  975: "SAINT-PIERRE-ET-MIQUELON",
  976: "MAYOTTE",
  977: "SAINT-BARTHELEMY",
  978: "SAINT-MARTIN",
  984: "TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES",
  986: "WALLIS-ET-FUTUNA",
  987: "POLYNESIE FRANCAISE",
  988: "NOUVELLE-CALEDONIE",
  989: "ILE DE CLIPPERTON"
};

export const REGIONS_LIST = [
  { code: "11", label: "Île-de-France" },
  { code: "24", label: "Centre-Val de Loire" },
  { code: "27", label: "Bourgogne-Franche-Comté" },
  { code: "28", label: "Normandie" },
  { code: "32", label: "Hauts-de-France" },
  { code: "44", label: "Grand Est" },
  { code: "52", label: "Pays de la Loire" },
  { code: "53", label: "Bretagne" },
  { code: "75", label: "Nouvelle-Aquitaine" },
  { code: "76", label: "Occitanie" },
  { code: "84", label: "Auvergne-Rhône-Alpes" },
  { code: "93", label: "Provence-Alpes-Côte d'Azur" },
  { code: "94", label: "Corse" },
  { code: "01", label: "Guadeloupe" },
  { code: "02", label: "Martinique" },
  { code: "03", label: "Guyane" },
  { code: "04", label: "La Réunion" },
 { code: "05", label: "Saint-Pierre-et-Miquelon" },
  { code: "06", label: "Mayotte" },
  { code: "07", label: "Saint-Barthélemy" },
  { code: "08", label: "Saint-Martin" },
  { code: "09", label: "Wallis-et-Futuna" },
  { code: "10", label: "Polynésie Française" },
  { code: "12", label: "Nouvelle-Calédonie" }
];

export const DEFAULT_DELEGATIONS = [
  {
    label: "Délégation Est et COM",
    depCodes: [
      "01",
      "03",
      "07",
      "15",
      "26",
      "38",
      "42",
      "43",
      "63",
      "69",
      "73",
      "74",
      "04",
      "05",
      "06",
      "13",
      "83",
      "84",
      "2A",
      "2B",
      "971",
      "972",
      "973",
      "974",
      "976",
      "975", 
      "977",
      "978",
      "984",
      "986",
      "987",
      "988" // Ajout des COM manquantes
    ],
  },
  {
    label: "Délégation Ile-de-France",
    depCodes: ["75", "77", "78", "91", "92", "93", "94", "95"],
  },
  {
    label: "Délégation Nord",
    depCodes: ["59", "62", "02", "60", "80", "14", "27", "50", "61", "76"],
  },
  {
    label: "Délégation Centre-Ouest",
    depCodes: [
      "22",
      "29",
      "35",
      "56",
      "44",
      "49",
      "53",
      "72",
      "85",
      "18",
      "28",
      "36",
      "37",
      "41",
      "45",
    ],
  },
  {
    label: "Délégation Centre-Est",
    depCodes: [
      "08",
      "10",
      "51",
      "52",
      "54",
      "55",
      "57",
      "88",
      "67",
      "68",
      "21",
      "25",
      "39",
      "58",
      "70",
      "71",
      "89",
      "90",
    ],
  },
  {
    label: "Délégation Nouvelle-Aquitaine",
    depCodes: [
      "16",
      "17",
      "19",
      "23",
      "24",
      "33",
      "40",
      "47",
      "64",
      "79",
      "86",
      "87",
    ],
  },
  {
    label: "Délégation Occitanie",
    depCodes: [
      "09",
      "11",
      "12",
      "30",
      "31",
      "32",
      "34",
      "46",
      "48",
      "65",
      "66",
      "81",
      "82",
    ],
  },
];

export const GEO_ABBR = [
  { full: "SAINT-", short: "St-" },
  { full: "SAINTE-", short: "Ste-" },
  { full: "SAINTS-", short: "Sts-" },
  { full: "NOTRE-DAME", short: "N.D." },
  { full: "MONTAGNE", short: "Mtgne" },
  { full: "ARRONDISSEMENT", short: "Arr." },
  { full: "DEPARTEMENT", short: "Dép." },
  { full: "REGION", short: "Rég." },
];
